version: "3.4"

services:
  entry-backup:
    image: entry-backup
    build:
      context: src/service
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      PORT: 80
      HOST: localhost:3000
    volumes:
      - "./src/service/temp:/usr/src/app/temp"
    ports:
      - 3000:80
